#include "include/caplogger.hpp"
#include <vector>
#include <sstream>

DEFINE_CAP_LOG_CHANNEL(CHANNEL_ONE, 2, FULLY_ENABLED)
  DEFINE_CAP_LOG_CHANNEL(CHANNEL_TWO, 5, FULLY_DISABLED, CHANNEL_ONE)
    DEFINE_CAP_LOG_CHANNEL(CHANNEL_TWO_B, 8, FULLY_ENABLED, CHANNEL_TWO) 
  DEFINE_CAP_LOG_CHANNEL(CHANNEL_THREE, 8, FULLY_ENABLED, CHANNEL_ONE)
    DEFINE_CAP_LOG_CHANNEL(CHANNEL_THREE_B, 4, ENABLED_NO_OUTPUT, CHANNEL_THREE)
      DEFINE_CAP_LOG_CHANNEL(CHANNEL_THREE_C, 4, FULLY_ENABLED, CHANNEL_THREE_B)
      
///////

int main() {
  
  CAP_LOG_BLOCK_NO_THIS(CAP::CHANNEL::DEFAULT, "main");

  {
    CAP_LOG_SCOPE_NO_THIS(CHANNEL_ONE, "main");
  }
  
  printf("Channel CHANNEL_ONE is %zu\n", (size_t) CAP_CHANNEL_OUTPUT_MODE(CAP_LOG_CHANNEL_STRING(CHANNEL_ONE)));
  printf("Channel CHANNEL_TWO is %zu\n", (size_t) CAP_CHANNEL_OUTPUT_MODE(CAP_LOG_CHANNEL_STRING(CHANNEL_TWO)));
  printf("Channel CHANNEL_TWO_B is %zu\n", (size_t) CAP_CHANNEL_OUTPUT_MODE(CAP_LOG_CHANNEL_STRING(CHANNEL_TWO_B)));
  printf("Channel CHANNEL_THREE is %zu\n", (size_t) CAP_CHANNEL_OUTPUT_MODE(CAP_LOG_CHANNEL_STRING(CHANNEL_THREE)));
  printf("Channel CHANNEL_THREE_B is %zu\n", (size_t) CAP_CHANNEL_OUTPUT_MODE(CAP_LOG_CHANNEL_STRING(CHANNEL_THREE_B)));
  printf("Channel CHANNEL_THREE_C is %zu\n", (size_t) CAP_CHANNEL_OUTPUT_MODE(CAP_LOG_CHANNEL_STRING(CHANNEL_THREE_C)));

  return 0;
}
