#pragma once

#ifdef ENABLE_CAP_LOGGER
#define ENABLE_CAP_LOGGER_IMPL

#ifdef CAP_LOGGER_FORCE_ALL_CHANNELS_ENABLED
#define CAP_LOGGER_FORCE_ALL_CHANNELS_ENABLED_IMPL
#endif // CAP_LOGGER_FORCE_ALL_CHANNELS_ENABLED

#define CAP_LOGGER_ROOT_CHANNEL_MODE ChannelEnabledMode::FULLY_ENABLED

#endif // ENABLE_CAP_LOGGER

